max_clock = 100000000
clock_granu = 1
log_level = "INFO"
log_name = "/dev/null"
edges = [
    [
        "Host",
        "Switch-0",
    ],
    [
        "Switch-0",
        "SrcMem-0",
    ],
    [
        "Switch-0",
        "DstMem-0",
    ],
    [
        "Switch-1",
        "SrcMem-1",
    ],
    [
        "Switch-1",
        "DstMem-1",
    ],
    [
        "Switch-2",
        "SrcMem-2",
    ],
    [
        "Switch-2",
        "DstMem-2",
    ],
    [
        "Switch-3",
        "SrcMem-3",
    ],
    [
        "Switch-3",
        "DstMem-3",
    ],
    [
        "Switch-0",
        "Switch-1",
    ],
    [
        "Switch-1",
        "Switch-2",
    ],
    [
        "Switch-2",
        "Switch-3",
    ],
]

[devices]
SrcMem-0 = "DRAMsim3Interface"
SrcMem-1 = "DRAMsim3Interface"
SrcMem-2 = "DRAMsim3Interface"
SrcMem-3 = "DRAMsim3Interface"
DstMem-0 = "DRAMsim3Interface"
DstMem-1 = "DRAMsim3Interface"
DstMem-2 = "DRAMsim3Interface"
DstMem-3 = "DRAMsim3Interface"
Switch-0 = "Switch"
Switch-1 = "Switch"
Switch-2 = "Switch"
Switch-3 = "Switch"
Host = "Requester"

[SrcMem-0]
tick_per_clock = 1
process_time = 40
start = 0
capacity = 1073741824
wr_ratio = 0.0
config_file = "DRAMsim3/configs/DDR4_8Gb_x8_3200.ini"
output_dir = "output"

[SrcMem-1]
tick_per_clock = 1
process_time = 40
start = 2147483648
capacity = 1073741824
wr_ratio = 0.0
config_file = "DRAMsim3/configs/DDR4_8Gb_x8_3200.ini"
output_dir = "output"

[SrcMem-2]
tick_per_clock = 1
process_time = 40
start = 4294967296
capacity = 1073741824
wr_ratio = 0.0
config_file = "DRAMsim3/configs/DDR4_8Gb_x8_3200.ini"
output_dir = "output"

[SrcMem-3]
tick_per_clock = 1
process_time = 40
start = 6442450944
capacity = 1073741824
wr_ratio = 0.0
config_file = "DRAMsim3/configs/DDR4_8Gb_x8_3200.ini"
output_dir = "output"

[DstMem-0]
tick_per_clock = 1
process_time = 40
start = 1073741824
capacity = 1073741824
wr_ratio = 1.0
config_file = "DRAMsim3/configs/DDR4_8Gb_x8_3200.ini"
output_dir = "output"

[DstMem-1]
tick_per_clock = 1
process_time = 40
start = 3221225472
capacity = 1073741824
wr_ratio = 1.0
config_file = "DRAMsim3/configs/DDR4_8Gb_x8_3200.ini"
output_dir = "output"

[DstMem-2]
tick_per_clock = 1
process_time = 40
start = 5368709120
capacity = 1073741824
wr_ratio = 1.0
config_file = "DRAMsim3/configs/DDR4_8Gb_x8_3200.ini"
output_dir = "output"

[DstMem-3]
tick_per_clock = 1
process_time = 40
start = 7516192768
capacity = 1073741824
wr_ratio = 1.0
config_file = "DRAMsim3/configs/DDR4_8Gb_x8_3200.ini"
output_dir = "output"

[Switch-0]
delay = 25

[Switch-1]
delay = 25

[Switch-2]
delay = 25

[Switch-3]
delay = 25

[Host]
q_capacity = 32
cache_capacity = 8192
cache_delay = 12
issue_delay = 100
coherent = false
burst_size = 1
block_size = 64
interleave_type = "stream"
interleave_param = 12800
hot_req_ratio = 0.5
hot_region_ratio = 0.5
trace_file = ""


